name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes

  build:
    name: Build Binary
    needs: create-release
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            name: powertools-macos-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: powertools-macos-x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: powertools-linux-x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '25.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd powertools-cli
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare Binary
        run: |
          cd powertools-cli/target/${{ matrix.target }}/release
          tar czf ${{ matrix.name }}.tar.gz powertools
          mv ${{ matrix.name }}.tar.gz ${{ github.workspace }}/

      - name: Generate SHA256 Checksum
        run: |
          shasum -a 256 ${{ matrix.name }}.tar.gz > ${{ matrix.name }}.tar.gz.sha256

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ matrix.name }}.tar.gz \
            ${{ matrix.name }}.tar.gz.sha256 \
            --repo ${{ github.repository }}

  update-homebrew:
    name: Update Homebrew Formula
    needs: build
    runs-on: ubuntu-latest

    env:
      HOMEBREW_TAP_REPO: zachswift615/homebrew-powertools
      FORMULA_NAME: powertools

    steps:
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Download release assets
        run: |
          VERSION=${{ steps.get_version.outputs.version }}

          # Download all release assets with checksums
          gh release download "v${VERSION}" \
            --repo ${{ github.repository }} \
            --pattern "*.tar.gz.sha256"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract checksums
        id: checksums
        run: |
          # Read checksums from downloaded files
          ARM64_SHA=$(cat powertools-macos-arm64.tar.gz.sha256 | awk '{print $1}')
          X86_64_SHA=$(cat powertools-macos-x86_64.tar.gz.sha256 | awk '{print $1}')
          LINUX_SHA=$(cat powertools-linux-x86_64.tar.gz.sha256 | awk '{print $1}')

          echo "arm64_sha=$ARM64_SHA" >> $GITHUB_OUTPUT
          echo "x86_64_sha=$X86_64_SHA" >> $GITHUB_OUTPUT
          echo "linux_sha=$LINUX_SHA" >> $GITHUB_OUTPUT

          echo "Checksums extracted:"
          echo "  ARM64:  $ARM64_SHA"
          echo "  x86_64: $X86_64_SHA"
          echo "  Linux:  $LINUX_SHA"

      - name: Checkout Homebrew tap
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HOMEBREW_TAP_REPO }}
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Update formula
        run: |
          cd homebrew-tap/Formula
          VERSION=${{ steps.get_version.outputs.version }}
          ARM64_SHA=${{ steps.checksums.outputs.arm64_sha }}
          X86_64_SHA=${{ steps.checksums.outputs.x86_64_sha }}
          LINUX_SHA=${{ steps.checksums.outputs.linux_sha }}

          # Update version
          sed -i "s/version \".*\"/version \"$VERSION\"/" ${{ env.FORMULA_NAME }}.rb

          # Update ARM64 SHA
          sed -i "s/REPLACE_WITH_ARM64_SHA256/$ARM64_SHA/" ${{ env.FORMULA_NAME }}.rb
          sed -i "/powertools-macos-arm64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"$ARM64_SHA\"/" ${{ env.FORMULA_NAME }}.rb

          # Update x86_64 SHA
          sed -i "s/REPLACE_WITH_X86_64_SHA256/$X86_64_SHA/" ${{ env.FORMULA_NAME }}.rb
          sed -i "/powertools-macos-x86_64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"$X86_64_SHA\"/" ${{ env.FORMULA_NAME }}.rb

          # Update Linux SHA
          sed -i "s/REPLACE_WITH_LINUX_SHA256/$LINUX_SHA/" ${{ env.FORMULA_NAME }}.rb
          sed -i "/powertools-linux-x86_64.tar.gz/,/sha256/ s/sha256 \".*\"/sha256 \"$LINUX_SHA\"/" ${{ env.FORMULA_NAME }}.rb

          echo "Updated formula:"
          cat ${{ env.FORMULA_NAME }}.rb

      - name: Commit and push
        run: |
          cd homebrew-tap
          VERSION=${{ steps.get_version.outputs.version }}

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Formula/${{ env.FORMULA_NAME }}.rb

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ${{ env.FORMULA_NAME }} to v${VERSION}" \
                       -m "Automated update with SHA256 checksums from release." \
                       -m "ARM64:  ${{ steps.checksums.outputs.arm64_sha }}" \
                       -m "x86_64: ${{ steps.checksums.outputs.x86_64_sha }}" \
                       -m "Linux:  ${{ steps.checksums.outputs.linux_sha }}"

            git push
            echo "✅ Homebrew formula updated successfully!"
          fi

      - name: Verify formula
        run: |
          cd homebrew-tap
          cat Formula/${{ env.FORMULA_NAME }}.rb

          # Check that no placeholders remain
          if grep -q "REPLACE_WITH" Formula/${{ env.FORMULA_NAME }}.rb; then
            echo "❌ Error: Placeholders still present in formula"
            exit 1
          fi

          echo "✅ Formula verification passed"
