name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes

  build:
    name: Build Binary
    needs: create-release
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            name: powertools-macos-arm64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: powertools-macos-x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: powertools-linux-x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build
        run: |
          cd powertools-cli
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare Binary
        run: |
          cd powertools-cli/target/${{ matrix.target }}/release
          tar czf ${{ matrix.name }}.tar.gz powertools
          mv ${{ matrix.name }}.tar.gz ${{ github.workspace }}/

      - name: Generate SHA256 Checksum
        run: |
          shasum -a 256 ${{ matrix.name }}.tar.gz > ${{ matrix.name }}.tar.gz.sha256

      - name: Upload Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} \
            ${{ matrix.name }}.tar.gz \
            ${{ matrix.name }}.tar.gz.sha256 \
            --repo ${{ github.repository }}
